apps:
  development:
    server: jbrunton-com-development
    branches: '*'

  staging:
    server: jbrunton-com-staging
    branches: master
    checks:
      origin: true

  production:
    server: jbrunton-com
    branches: master
    tag: 'RELEASE_%Y%m%dT%H%M%S%z'
    checks:
      origin: true
      staged: true
