apps:
  development:
    server: jbrunton-com-development
    branches: '*'

  staging:
    server: jbrunton-com-staging
    branches: master
    checks:
      origin: true

  production:
    server: jbrunton-com
    branches: master
    tag: 'RELEASE:%FT%T%:z'
    push: release
    checks:
      origin: true
      staged: true
