apps:
  development:
    heroku: jbrunton-com-development

  staging:
    heroku: jbrunton-com-staging
    checks:
      pushed: true
      branch: master

  production:
    heroku: jbrunton-com
    tag: 'RELEASE_%Y%m%dT%H%M%S%z'
    checks:
      pushed: true
      branch: master
      staged: true
