# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Brunton
description: > # this means to ignore newlines until "baseurl:"
  Advocate for software craftsmanship, Lean methodologies and self-organising
  teams. Sustainable development (i.e. the continuous delivery of value) is what
  happens when you get these things right.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.jbrunton.com" # the base hostname & protocol for your site
github_username:  jbrunton

category_names:
  lean: Lean Thinking
  teamwork: Teamwork

# Build settings
markdown: kramdown
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
