travis_repo: jbrunton/jbrunton.com

load_configs:
  private_keys:
    repository: git@github.com:jbrunton/jbrunton.com-config.git
    file: config/heroploy.yml

common:
  required:
    - facebook_app_id
    - facebook_app_secret
  variables:
    admin_users: 36804649

environments:
  local:
    variables:
      facebook_app_id: 1400932756832068
      google_analytics_id: UA-49182422-1
  
  development:
    app: jbrunton-com-development
    variables:
      facebook_app_id: 523872661065702
      google_analytics_id: UA-49182422-1
      RACK_ENV: development
      RAILS_ENV: development

  staging:
    app: jbrunton-com-staging
    variables:
      facebook_app_id: 1408788939378363
      RACK_ENV: production
      RAILS_ENV: production
    checks:
      pushed: true
      branch: master
      travis: true

  production:
    app: jbrunton-com
    tag: 'RELEASE_%Y%m%dT%H%M%S%z'
    variables:
      facebook_app_id: 661405633896129
      google_analytics_id: UA-49182422-2
      RACK_ENV: production
      RAILS_ENV: production
    checks:
      pushed: true
      branch: master
      staged: true
      travis: true
